---
# Source: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-gha-rs-no-permission
  namespace: default
  labels:
    helm.sh/chart: gha-rs-0.12.1
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: release-name
    actions.github.com/scale-set-namespace: default
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-gha-rs-manager
  namespace: default
  labels:
    helm.sh/chart: gha-rs-0.12.1
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: release-name
    actions.github.com/scale-set-namespace: default
    app.kubernetes.io/component: manager-role
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-gha-rs-manager
  namespace: default
  labels:
    helm.sh/chart: gha-rs-0.12.1
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: release-name
    actions.github.com/scale-set-namespace: default
    app.kubernetes.io/component: manager-role-binding
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    arc-gha-rs-controller
  namespace: 
    arc-systems
---
# Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: release-name
  namespace: default
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.12.1
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: release-name
    actions.github.com/scale-set-namespace: default
  annotations:
    actions.github.com/values-hash: 480130c7d89af06ba4b9b6c9163d464985ada0814fd542aede77ba3d5401226
    actions.github.com/cleanup-manager-role-binding: release-name-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: release-name-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: release-name-gha-rs-no-permission

spec:
  githubConfigUrl: https://github.com/matoruru/matoru.ru
  githubConfigSecret: pre-defined-secret
  maxRunners: 3
  minRunners: 0

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: release-name-gha-rs-no-permission
      containers:
      
      - name: runner
        command: 
          - /home/runner/run.sh
        image: 
          matoruru/gha-runner-base:latest
        imagePullPolicy: 
          IfNotPresent
