apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-sample-apps
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: istio-sample
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: manifests/apps/manifests/istio-sample-apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
