apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  hostnames:
  - prometheus.matoru.ru
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-grafana
      port: 80
