apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testpvc
spec:
  selector:
    matchLabels:
      app: testpvc
  template:
    metadata:
      labels:
        app: testpvc
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: bb
        command:
        - sh
        - -c
        - cd /app; while true; do  echo [$NODE_NAME] $(date) | tee -a output.txt; sleep 1s; done
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: myvol
          mountPath: /app
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: myclaim
