apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-subdir-external-provisioner
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-e8690726-e834-4021-a1a1-1bf26bdb71b6
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: myclaim
    namespace: test-pvc
  nfs:
    path: /export/nfs/home-kubernetes/pvc-test-pvc-myclaim
    server: 192.168.11.151
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  volumeMode: Filesystem
