apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: my-wordpress
  data:
  - secretKey: wordpress-password
    remoteRef:
      key: secret/wp-wordpress-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: my-mariadb
  data:
  - secretKey: mariadb-password
    remoteRef:
      key: secret/wp-mariadb-password
  - secretKey: mariadb-root-password
    remoteRef:
      key: secret/wp-mariadb-root-password
