apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-dex-oidc

resources:
- sa.yaml
- deployment.yaml

configMapGenerator:
- name: configmap-sourcecode
  files:
  - assets/index.js
  - assets/init.sh
