apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: akv-secret
  data:
  - secretKey: root-user
    remoteRef:
      key: secret/minio-root-user
  - secretKey: root-password
    remoteRef:
      key: secret/minio-root-password
