apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: nextcloud-db
  labels:
    team: acid
spec:
  teamId: acid
  postgresql:
    version: "16"
  numberOfInstances: 2
  volume:
    size: 10Gi
    storageClass: fast
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
