apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb-nextcloud-metadata
spec:
  version: v8.1.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 2
    storageClassName: fast
    requests:
      storage: 10Gi
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 2
    storageClassName: fast
    requests:
      cpu: 250m
      memory: 500Mi
      storage: 50Gi
    limits:
      cpu: 1000m
      memory: 1Gi
    config: {}
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 2
    service:
      type: ClusterIP
    config: {}
