apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "*.k8s.matoru.ru"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
