apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# CRD for Cilium Gateway API
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml

- gateway.yaml
