apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast # SSD mounted on Ubuntu
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Retain
parameters:
  pathPattern: pvc-${.PVC.namespace}-${.PVC.name}
  archiveOnDelete: 'false'
