apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow # HDD mounted on Ubuntu
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.sc.parameters.server }}
  path: {{ .Values.sc.parameters.path }}
  readOnly: "false"
