apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow # HDD mounted on Ubuntu
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  pathPattern: pvc-${.PVC.namespace}-${.PVC.name}
