apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-homepage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: cloudflared-homepage-secret
  data:
  - secretKey: CLOUDFLARED_TOKEN
    remoteRef:
      key: secret/cloudflared-homepage-token
