apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-home-k8s-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: cloudflared-home-k8s-secret
  data:
  - secretKey: CLOUDFLARED_TOKEN
    remoteRef:
      key: secret/cloudflared-home-k8s-token
