apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
- ns.yaml
- deployment.yaml
- ../../base/workload-identities/Home-Kubernetes/
- ../../base/external-secrets/
- externalsecret.yaml
