metadata:
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/matoruru/home-kubernetes
    targetRevision: main

gha:
  chart:
    version: 0.9.3

istio:
  repoURL: https://istio-release.storage.googleapis.com/charts
  version: 1.23.0

nextcloud:
  host: nextcloud.matoru.ru
