metadata:
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/matoruru/home-kubernetes
    targetRevision: upgrade-gha-runner

gha:
  chart:
    version: 0.12.1

istio:
  repoURL: https://istio-release.storage.googleapis.com/charts
  version: 1.23.0
