spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/matoruru/home-kubernetes
    targetRevision: main

gha:
  chart:
    version: 0.9.3