apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pre-defined-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: pre-defined-secret
  data:
  - secretKey: github_app_id
    remoteRef:
      key: secret/arc-github-app-id
  - secretKey: github_app_installation_id
    remoteRef:
      key: secret/arc-github-app-installation-id
  - secretKey: github_app_private_key
    remoteRef:
      key: secret/arc-github-app-private-key
