apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: oidc.azure.clientSecret
    remoteRef:
      key: secret/oidc-azure-clientSecret
