apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: oidc.azure.clientSecret
    remoteRef:
      key: secret/oidc-azure-clientSecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: github-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/matoruru
        type: git
        githubAppID: "1073910"
        githubAppInstallationID: "57796268"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: secret/argocd-github-creds-githubAppPrivateKey

