apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
spec:
  hostnames:
  - argocd.matoru.ru
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: web
      port: 80
