apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: akv-secret
  data:
  - secretKey: PROMETHEUS_CLIENT_SECRET
    remoteRef:
      key: secret/prometheus-client-secret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: PROMETHEUS_CLIENT_ID
    remoteRef:
      key: secret/prometheus-client-id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: TENANT_ID
    remoteRef:
      key: secret/tenant-id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
