apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml

patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
  patch: |-
    - op: add
      path: /spec/template/spec/initContainers/0/env/-
      value:
        name: CALICO_IPV4POOL_CIDR
        value: 10.244.0.0/16
