apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: mysecret
  data:
  - secretKey: akv2k8s-client-id
    remoteRef:
      key: secret/akv2k8s-client-id
  - secretKey: akv2k8s-tenant-id
    remoteRef:
      key: secret/akv2k8s-tenant-id
