apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://home-k8s-keyvault.vault.azure.net
      serviceAccountRef:
        name: akv2k8s-wi-sa
