apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv2k8-keyvault
  namespace: akv2k8s
spec:
  provider: azure
  secretObjects:
  - secretName: akv2k8s-creds
    type: Opaque
    data:
    - key: AZURE_CLIENT_ID
      objectName: akv2k8s-client-id
    - key: AZURE_TENANT_ID
      objectName: akv2k8s-tenant-id
    - key: AZURE_CLIENT_SECRET
      objectName: akv2k8s-client-secret
  parameters:
    clientID: 34de22c5-a3d1-439e-89f8-3b01ca073e1e
    tenantId: 640dd2c2-336d-4abf-b0ee-0024877ea3fb
    keyvaultName: home-k8s-keyvault
    objects:  |
      array:
      - |
        objectName: akv2k8s-client-id
        objectType: secret
      - |
        objectName: akv2k8s-tenant-id
        objectType: secret
      - |
        objectName: akv2k8s-client-secret
        objectType: secret
