apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8s
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: akv2k8s
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/akv2k8s
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
