apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: dex
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    targetRevision: 0.19.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
