apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.4.4
    helm:
      valuesObject:
        fullnameOverride: argocd
        configs:
          cm:
            admin.enabled: false
            # Enabling Exec tab
            exec.enabled: 'true'
            # SSO: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/
            url: https://argocd.matoru.ru/ # Replace with the external base URL of your Argo CD
            oidc.config: |
              name: Azure
              issuer: https://login.microsoftonline.com/640dd2c2-336d-4abf-b0ee-0024877ea3fb/v2.0
              clientID: 43d9ca70-41c6-4210-a3cc-eb7717b1f4bc
              clientSecret: $oidc.azure.clientSecret
              requestedIDTokenClaims:
                groups:
                  essential: true
              requestedScopes:
              - openid
              - profile
              - email
          rbac: 
            policy.default: ''
            policy.csv: |
              g, Admin, role:admin
              g, ReadOnly, role:readonly
            scopes: '[roles]'
        dex:
          enabled: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
