apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-workload-identity-webhook
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: azure-workload-identity-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: workload-identity-webhook
    repoURL: https://azure.github.io/azure-workload-identity/charts
    targetRevision: 1.3.0
    helm:
      valuesObject:
        azureTenantID: 640dd2c2-336d-4abf-b0ee-0024877ea3fb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
