apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-secret-store-csi-driver
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: azure-secret-store-csi-driver
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: csi-secrets-store-provider-azure
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    targetRevision: 1.5.6
    helm:
      valuesObject:
        secrets-store-csi-driver:
          syncSecret.enabled: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
