apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: datadog
spec:
  destination:
    namespace: datadog
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/datadog
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  # - chart: datadog-operator
  #   repoURL: https://helm.datadoghq.com/datadog
  #   targetRevision: 1.8.6
  #   helm:
  #     releaseName: datadog-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
