apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/descheduler
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler
    targetRevision: 0.31.0
    helm:
      valuesObject:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
