apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler
    targetRevision: 0.31.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
