apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: dex
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    targetRevision: 0.19.1
    helm:
      valuesObject:
        config:
          issuer: https://iss.matoru.ru
          storage:
            type: etcd
            config:
              endpoints:
              - http://0.0.0.0:2379
              caFile: /etc/dex/etcd/ca.crt
              certFile: /etc/dex/etcd/client.crt
              keyFile: /etc/dex/etcd/client.key
          web:
            http: 0.0.0.0:5556
          oauth2:
            skipApprovalScreen: true
            responseTypes:
            - code
            - id_token
            - token
          staticClients:
          - id: kubernetes
            name: kubernetes
            redirectURIs:
            - "https://kubernetes.default.svc/oauth2/callback"
            secret: kubernetes-client-secret
          providers:
          - type: oidc
            id: my-provider
            name: My OIDC Provider
            config:
              issuer: https://iss.matoru.ru
              clientID: my-client-id
              clientSecret: my-client-secret
              scopes:
                - openid
                - profile
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: iss.matoru.ru
              paths:
                - path: /
                  pathType: Prefix
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
