apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: dex
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    targetRevision: 0.19.1
    helm:
      valuesObject:
        config:
          issuer: https://iss.matoru.ru
          storage:
            type: memory
          enablePasswordDB: true
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: iss.matoru.ru
              paths:
                - path: /
                  pathType: Prefix
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
