apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.1.4
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
