apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner-controller
  namespace: argocd
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/gha-runner-scale-set-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: arc
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: raspi-runner-set-matoruru
      valuesObject:
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        githubConfigUrl: https://github.com/matoruru/matoruru
        githubConfigSecret: pre-defined-secret
        maxRunners: 1
        minRunners: 0
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/actions/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
            - name: init-dind-rootless
              image: docker:dind-rootless
              command:
              - sh
              - -c
              - |
                set -x
                cp -a /etc/. /dind-etc/
                echo 'runner:x:1001:1001:runner:/home/runner:/bin/ash' >> /dind-etc/passwd
                echo 'runner:x:1001:' >> /dind-etc/group
                echo 'runner:100000:65536' >> /dind-etc/subgid
                echo 'runner:100000:65536' >>  /dind-etc/subuid
                chmod 755 /dind-etc;
                chmod u=rwx,g=rx+s,o=rx /dind-home
                chown 1001:1001 /dind-home
              securityContext:
                runAsUser: 0
              volumeMounts:
              - mountPath: /dind-etc
                name: dind-etc
              - mountPath: /dind-home
                name: dind-home
            containers:
            - name: runner
              image: matoruru/gha-runner-matoruru:latest
              command: ["/home/runner/run.sh"]
              env:
              - name: DOCKER_HOST
                value: unix:///home/runner/var/run/docker.sock
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
            - name: dind
              image: docker:dind-rootless
              args: ["dockerd", "--host=unix:///home/runner/var/run/docker.sock"]
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
              - name: dind-externals
                mountPath: /home/runner/externals
              - name: dind-etc
                mountPath: /etc
              - name: dind-home
                mountPath: /home/runner
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-etc
              emptyDir: {}
            - name: dind-home
              emptyDir: {}
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: raspi-runner-set-playground
      valuesObject:
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        githubConfigUrl: https://github.com/matoruru/playground
        githubConfigSecret: pre-defined-secret
        maxRunners: 1
        minRunners: 0
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/actions/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
            - name: init-dind-rootless
              image: docker:dind-rootless
              command:
              - sh
              - -c
              - |
                set -x
                cp -a /etc/. /dind-etc/
                echo 'runner:x:1001:1001:runner:/home/runner:/bin/ash' >> /dind-etc/passwd
                echo 'runner:x:1001:' >> /dind-etc/group
                echo 'runner:100000:65536' >> /dind-etc/subgid
                echo 'runner:100000:65536' >>  /dind-etc/subuid
                chmod 755 /dind-etc;
                chmod u=rwx,g=rx+s,o=rx /dind-home
                chown 1001:1001 /dind-home
              securityContext:
                runAsUser: 0
              volumeMounts:
              - mountPath: /dind-etc
                name: dind-etc
              - mountPath: /dind-home
                name: dind-home
            containers:
            - name: runner
              image: matoruru/gha-runner-playground:latest
              command: ["/home/runner/run.sh"]
              env:
              - name: DOCKER_HOST
                value: unix:///home/runner/var/run/docker.sock
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
            - name: dind
              image: docker:dind-rootless
              args: ["dockerd", "--host=unix:///home/runner/var/run/docker.sock"]
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
              - name: dind-externals
                mountPath: /home/runner/externals
              - name: dind-etc
                mountPath: /etc
              - name: dind-home
                mountPath: /home/runner
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-etc
              emptyDir: {}
            - name: dind-home
              emptyDir: {}
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: raspi-runner-set-matoru-ru
      valuesObject:
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        githubConfigUrl: https://github.com/matoruru/matoru.ru
        githubConfigSecret: pre-defined-secret
        maxRunners: 1
        minRunners: 0
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/actions/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
            - name: init-dind-rootless
              image: docker:dind-rootless
              command:
              - sh
              - -c
              - |
                set -x
                cp -a /etc/. /dind-etc/
                echo 'runner:x:1001:1001:runner:/home/runner:/bin/ash' >> /dind-etc/passwd
                echo 'runner:x:1001:' >> /dind-etc/group
                echo 'runner:100000:65536' >> /dind-etc/subgid
                echo 'runner:100000:65536' >>  /dind-etc/subuid
                chmod 755 /dind-etc;
                chmod u=rwx,g=rx+s,o=rx /dind-home
                chown 1001:1001 /dind-home
              securityContext:
                runAsUser: 0
              volumeMounts:
              - mountPath: /dind-etc
                name: dind-etc
              - mountPath: /dind-home
                name: dind-home
            containers:
            - name: runner
              image: matoruru/gha-runner-playground:latest
              command: ["/home/runner/run.sh"]
              env:
              - name: DOCKER_HOST
                value: unix:///home/runner/var/run/docker.sock
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
            - name: dind
              image: docker:dind-rootless
              args: ["dockerd", "--host=unix:///home/runner/var/run/docker.sock"]
              securityContext:
                privileged: true
                runAsUser: 1001
                runAsGroup: 1001
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /home/runner/var/run
              - name: dind-externals
                mountPath: /home/runner/externals
              - name: dind-etc
                mountPath: /etc
              - name: dind-home
                mountPath: /home/runner
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-etc
              emptyDir: {}
            - name: dind-home
              emptyDir: {}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: false
      prune: false # For avoiding infinite loop for AutoscalingListener.
