apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner-controller
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/gha-runner-scale-set-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: arc
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-playground
      valuesObject:
        githubConfigUrl: https://github.com/matoruru/playground
        {{- include "github-actions-runner-controller.valuesObject.base" . | nindent 8 }}
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-matoruru-homepage
      valuesObject:
        githubConfigUrl: https://github.com/matoruru/matoru.ru
        {{- include "github-actions-runner-controller.valuesObject.base" (merge (dict "runnerImage" "matoruru/gha-runner-base:latest") .) | nindent 8 }}
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-matoruru-profile
      valuesObject:
        githubConfigUrl: https://github.com/matoruru/matoruru
        {{- include "github-actions-runner-controller.valuesObject.base" . | nindent 8 }}
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-golang1-23-3
      valuesObject:
        githubConfigUrl: https://github.com/matoruru/matoru.ru
        {{- include "github-actions-runner-controller.valuesObject.base" (merge (dict "runnerImage" "golang:1.23.3") .) | nindent 8 }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: {}
