apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner-controller
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: arc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: {}
