apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner-controller
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/gha-runner-scale-set-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: arc
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-matoruru-homepage
      valuesObject:
        {{- include "github-actions-runner-controller.valuesObject.base" . | nindent 8 }}
        githubConfigUrl: https://github.com/matoruru/matoru.ru
        template:
          spec:
            containers:
              - name: runner
                image: matoruru/gha-runner-base:latest
                imagePullPolicy: IfNotPresent
                command: ["/home/runner/run.sh"]
  - chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: {{ .Values.gha.chart.version }}
    helm:
      releaseName: raspi-golang1-23-3
      valuesObject:
        {{- include "github-actions-runner-controller.valuesObject.base" . | nindent 8 }}
        githubConfigUrl: https://github.com/matoruru/bekidatta.com
        template:
          spec:
            containers:
              - name: runner
                image: matoruru/gha-runner-golang:1.23
                imagePullPolicy: IfNotPresent
                command: ["/home/runner/run.sh"]
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    #- ServerSideApply=true
    automated: {}
