apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: istio-ingress
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: gateway
    repoURL:  https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
