apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: base
    repoURL: {{ .Values.istio.repoURL }}
    targetRevision: {{ .Values.istio.version }}
  - chart: istiod
    repoURL: {{ .Values.istio.repoURL }}
    targetRevision: {{ .Values.istio.version }}
    helm:
      valuesObject:
        profile: ambient
  - chart: cni
    repoURL: {{ .Values.istio.repoURL }}
    targetRevision: {{ .Values.istio.version }}
    helm:
      valuesObject:
        profile: ambient
  - chart: ztunnel
    repoURL: {{ .Values.istio.repoURL }}
    targetRevision: {{ .Values.istio.version }}
  {{- include "istio.ignoreDifferences" . | nindent 2 }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: {}
