apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-prometheus
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/kube-prometheus-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.5.1
    helm:
      valuesObject:
        fullnameOverride: monitoring
        prometheus:
          annotations:
            argocd.argoproj.io/skip-health-check: 'true'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
