apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: loki-stack
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      valuesObject:
        # Grafana Loki: a log aggregation system designed to store and query logs
        loki:
          enabled: true
          schemaConfig:
            configs:
            - from: 2024-04-01
              store: tsdb
              object_store: s3
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
          server:
            http_server_read_timeout: 3m
            http_server_write_timeout: 3m
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4
          deploymentMode: SimpleScalable
          frontend:
            max_outstanding_per_tenant: 4096
            compress_responses: true
          backend:
            replicas: 3
          read:
            replicas: 3
          write:
            replicas: 3
          singleBinary:
            replicas: 0
          ingester:
            replicas: 0
          querier:
            max_concurrent: 2048
          query_range:
            split_queries_by_interval: 0
            parallelise_shardable_queries: true
          queryFrontend:
            replicas: 0
          queryScheduler:
            max_outstanding_requests_per_tenant: 4096
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomCompactor:
            replicas: 0
          bloomGateway:
            replicas: 0
          persistence:
            enabled: true
            storageClassName: fast
          limits_config:
            split_queries_by_interval: 15m
            max_query_parallelism: 32
        # Promtail: an agent which ships the contents of local logs to Grafana Loki instance
        promtail:
          enabled: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
