apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: nextcloud
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/nextcloud
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.2.1
    helm:
      valuesObject:
        nextcloud.host: nextcloud.matoru.ru
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
