apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: nextcloud
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/nextcloud
    repoURL: {{ .Values.spec.source.repoURL }}
    #targetRevision: {{ .Values.spec.source.targetRevision }}
    targetRevision: add-nextcloud
  - chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.2.1
    helm:
      valuesObject:
        internalDatabase:
          enabled: false
        externalDatabase:
          enabled: true
          type: postgresql
          existingSecret:
            enabled: true
            secretName: nextcloud-db-secret
            usernameKey: username
            passwordKey: password
            hostKey: host
            databaseKey: database
        nextcloud:
          host: {{ .Values.nextcloud.host }}
          objectStore:
            s3:
              enabled: true
              usePathStyle: true
              existingSecret: minio-secret
              secretKeys:
                host: minio-host
                accessKey: minio-nextcloud-user
                secretKey: minio-nextcloud-password
                bucket: minio-nextcloud-bucket
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: username
            passwordKey: password
          configs:
            logging.config.php: |-
              <?php
              $CONFIG = array (
                'log_type' => 'file',
                'logfile' => 'nextcloud.log',
                'loglevel' => 0,
                'logdateformat' => 'F d, Y H:i:s',
                'overwrite.cli.url' => 'https://{{ .Values.nextcloud.host }}',
                'overwriteprotocol' => 'https'
                );
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
