apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: prometheus-stack
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/prometheus-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.7.0
    helm:
      valuesObject:
        fullnameOverride: prometheus-stack
        prometheus:
          prometheusSpec:    
            storageSpec: 
              volumeClaimTemplate:
                spec:
                  storageClassName: slow
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
        grafana:
          envFromSecret: akv-secret
          grafana.ini:
            server:
              root_url: https://grafana.matoru.ru
            users:
              allow_sign_up: false
              auto_assign_org: true
              auto_assign_org_role: Viewer
            auth:
              disable_login_form: true
            auth.basic:
              enabled: false
            auth.azuread:
              name: Azure AD
              enabled: true
              allow_sign_up: true
              auto_login: true
              client_id: $__env{GRAFANA_CLIENT_ID}
              client_secret: $__env{GRAFANA_CLIENT_SECRET}
              scopes: openid email profile
              auth_url: https://login.microsoftonline.com/$__env{TENANT_ID}/oauth2/v2.0/authorize
              token_url: https://login.microsoftonline.com/$__env{TENANT_ID}/oauth2/v2.0/token
              allowed_domains: 
              allowed_group:
              allowed_organizations: $__env{TENANT_ID}
              role_attribute_strict: false
              allow_assign_grafana_admin: false
              skip_org_role_sync: false
              use_pkce: true
          additionalDataSources:
          - name: Loki
            type: loki
            uid: loki
            url: http://loki-stack.loki-stack:3100/
            access: proxy
            editable: false
            isDefault: false
          persistence:
            enabled: true
            type: pvc
            storageClassName: slow
            size: 5Gi
          # Because of this error: https://github.com/grafana/helm-charts/issues/752
          initChownData:
            enabled: false
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
