apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: storageclass
    repoURL: github.com/argoproj/argo-cd//manifests/cluster-install?ref=main
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
