apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/storageclass
    repoURL: https://github.com/matoruru/home-kubernetes
    targetRevision: add-storageclass
    helm:
      valuesObject:
        sc:
          parameters:
            server: 192.168.11.151
            path: /export/nfs/home-kubernetes
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
