apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: wordpress
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: manifests/tools/manifests/wordpress
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - chart: wordpress
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 23.1.17
    helm:
      valuesObject:
        # WordPress
        existingSecret: my-wordpress
        resourcesPreset: small
        htaccessPersistenceEnabled: true
        customHTAccessCM: custom-htaccess
        # WordPress cache
        wordpressConfigureCache: true
        memcached:
          enabled: true
        metrics:
          enabled: true
        persistence:
          storageClass: slow
          size: 100Gi
        # MariaDB
        mariadb:
          auth:
            existingSecret: my-mariadb
          primary:
            persistence:
              storageClass: slow
            resourcesPreset: small
        service:
          type: ClusterIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
