apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: matoru-ru
spec:
  selector:
    matchLabels:
      app: matoru.ru
  template:
    metadata:
      labels:
        app: matoru.ru
    spec:
      containers:
      - image: matoruru/matoru.ru:latest
        imagePullPolicy: Always
        name: web
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 20m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 500Mi
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 60
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 10
          periodSeconds: 1
