apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mesh
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: web
      port: 8080
