apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mesh
spec:
  parentRefs:
  - name: gateway-istio
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: web
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
