apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mesh
spec:
  parentRefs:
  - kind: Service
    name: gateway-istio
    port: 80
  matches:
  - path:
    type: PathPrefix
    value: /particles
  rules:
  - backendRefs:
    - name: web
      port: 8080
